# Generated by Django 2.0.6 on 2018-06-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_group_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateTimeField(max_length=255)),
                ('_home_team', models.CharField(max_length=255)),
                ('_visiting_team', models.CharField(max_length=255)),
                ('_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_predictor', models.DateTimeField(max_length=255)),
                ('_home_team_goals', models.PositiveSmallIntegerField()),
                ('_visiting_team_goals', models.PositiveSmallIntegerField(max_length=255)),
                ('_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.Match')),
            ],
        ),
    ]
